### PR TITLE
Attempt to add MacOS build

### LINKED ISSUE #9: Missing MacOS build of gst-plugins-bad
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/linus/anaconda3/envs/horus_ai:
#
# Name                    Version                   Build  Channel
anyio                     3.4.0                    pypi_0    pypi
asgiref                   3.4.1                    pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
blas                      1.0                         mkl  
blinker                   1.4                      pypi_0    pypi
blosc                     1.10.6                   pypi_0    pypi
boto3                     1.20.20                  pypi_0    pypi
botocore                  1.23.20                  pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2021.10.26           hecd8cb5_2  
cairo                     1.16.0            h0ab9d94_1001    conda-forge
certifi                   2021.5.30        py36h79c6626_0    conda-forge
charset-normalizer        2.0.9                    pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
contextlib2               21.6.0                   pypi_0    pypi
contextvars               2.4                      pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dataclasses               0.8                pyh4f3eec9_6  
elasticsearch             7.13.0                   pypi_0    pypi
ffmpeg                    4.3                  h0a44026_0    pytorch
filterpy                  1.4.5                    pypi_0    pypi
flask                     1.1.2                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
fontconfig                2.13.1            h10f422b_1005    conda-forge
freetype                  2.11.0               hd8bbffd_0  
fuzzywuzzy                0.18.0                   pypi_0    pypi
g-ir-build-tools          1.70.0           py36h32fca84_0    conda-forge
g-ir-host-tools           1.70.0               h7190600_0    conda-forge
gettext                   0.21.0               h7535e17_0  
glib                      2.70.1               hcf210ce_0    conda-forge
glib-tools                2.70.1               hcf210ce_0    conda-forge
gmp                       6.2.1                h23ab428_2  
gnutls                    3.6.15               hed9c0bf_0  
gobject-introspection     1.70.0           py36h21e8f9d_0    conda-forge
gputil                    1.4.0                    pypi_0    pypi
grpcio                    1.38.0                   pypi_0    pypi
gst-plugins-base          1.18.5               h63a84d5_2    conda-forge
gst-plugins-good          1.18.5               h9f3b8af_2    conda-forge
gstreamer                 1.18.5               h8cc6204_2    conda-forge
gunicorn                  20.1.0                   pypi_0    pypi
h11                       0.12.0                   pypi_0    pypi
httpcore                  0.13.7                   pypi_0    pypi
httptools                 0.2.0                    pypi_0    pypi
httpx                     0.18.2                   pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      3.3                      pypi_0    pypi
immutables                0.16                     pypi_0    pypi
importlib-metadata        4.8.2                    pypi_0    pypi
imutils                   0.5.4                    pypi_0    pypi
intel-openmp              2021.3.0          hecd8cb5_3375  
itsdangerous              2.0.1                    pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
jpeg                      9d                   h9ed2024_0  
kiwisolver                1.3.1                    pypi_0    pypi
kornia                    0.6.2                    pypi_0    pypi
lame                      3.100                h1de35cc_0  
lcms2                     2.12                 hf1fd2bf_0  
libcxx                    12.0.0               h2f01273_0  
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               3.0.1                h93005f0_2  
libgirepository           1.70.0               h128b86d_0    conda-forge
libglib                   2.70.1               hf1fb8c0_0    conda-forge
libiconv                  1.16                 h1de35cc_0  
libidn2                   2.3.2                h9ed2024_0  
libogg                    1.3.5                h9ed2024_1  
libopus                   1.3.1                hc929b4f_1    conda-forge
libpng                    1.6.37               ha441bb4_0  
libtasn1                  4.16.0               h9ed2024_0  
libtiff                   4.2.0                h87d7836_0  
libunistring              0.9.10               h9ed2024_0  
libuv                     1.40.0               haf1e3a3_0  
libvorbis                 1.3.7                h046ec9c_0    conda-forge
libwebp-base              1.2.0                h9ed2024_0  
libxml2                   2.9.12               hcdb78fc_0  
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               12.0.0               h0dcd299_1  
llvmlite                  0.36.0                   pypi_0    pypi
lz4-c                     1.9.3                h23ab428_1  
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.3.4                    pypi_0    pypi
mkl                       2021.3.0           hecd8cb5_517  
mkl-service               2.4.0            py36h9ed2024_0  
mkl_fft                   1.3.0            py36h4a7008c_2  
mkl_random                1.2.2            py36hb2f4e1b_0  
mlchain                   0.2.3                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1  
nettle                    3.7.3                h230ac6f_1  
norfair                   0.3.1                    pypi_0    pypi
numba                     0.53.1                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
numpy-base                1.16.6           py36h4850c68_3  
olefile                   0.46                     py36_0  
onnx                      1.10.2                   pypi_0    pypi
onnxruntime               1.9.0                    pypi_0    pypi
opencv-python             4.5.4.58                 pypi_0    pypi
openh264                  2.1.0                hd9629dc_0  
openjpeg                  2.4.0                h66ea3da_0  
openssl                   1.1.1l               h0d85af4_0    conda-forge
outcome                   1.1.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pcre                      8.45                 he49afe7_0    conda-forge
pillow                    8.3.1            py36ha4cf6ea_0  
pip                       21.2.2           py36hecd8cb5_0  
pixman                    0.38.0            h01d97ff_1003    conda-forge
pkg-config                0.29.2            hb849cc2_1008    conda-forge
protobuf                  3.19.1                   pypi_0    pypi
pycairo                   1.20.1           py36hd9b1a54_0    conda-forge
pygments                  2.10.0                   pypi_0    pypi
pygobject                 3.40.1           py36h21e8f9d_2    conda-forge
pyngrok                   5.1.0                    pypi_0    pypi
pynvml                    11.0.0                   pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
python                    3.6.13          haf480d7_2_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             0.19.2                   pypi_0    pypi
python-levenshtein        0.12.2                   pypi_0    pypi
python-multipart          0.0.5                    pypi_0    pypi
python_abi                3.6                     2_cp36m    conda-forge
pytorch                   1.10.0                  py3.6_0    pytorch
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1                  h9ed2024_0  
requests                  2.26.0                   pypi_0    pypi
rfc3986                   1.5.0                    pypi_0    pypi
rich                      10.15.2                  pypi_0    pypi
s3transfer                0.5.0                    pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
sentry-sdk                1.5.0                    pypi_0    pypi
setuptools                58.0.4           py36hecd8cb5_0  
six                       1.16.0             pyhd3eb1b0_0  
sniffio                   1.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sqlite                    3.36.0               hce871da_0  
starlette                 0.17.1                   pypi_0    pypi
tk                        8.6.11               h7bc2e8c_0  
toml                      0.10.2                   pypi_0    pypi
torchaudio                0.10.0                 py36_cpu    pytorch
torchvision               0.11.1                 py36_cpu    pytorch
tqdm                      4.62.3                   pypi_0    pypi
trio                      0.19.0                   pypi_0    pypi
typing_extensions         3.10.0.2           pyh06a4308_0  
urllib3                   1.26.7                   pypi_0    pypi
uvicorn                   0.15.0                   pypi_0    pypi
uvloop                    0.14.0                   pypi_0    pypi
watchgod                  0.7                      pypi_0    pypi
websockets                9.1                      pypi_0    pypi
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h1de35cc_0  
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.4.9                h322a384_0  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : horus_ai
    active env location : /Users/linus/anaconda3/envs/horus_ai
            shell level : 2
       user config file : /Users/linus/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/linus/anaconda3  (writable)
      conda av data dir : /Users/linus/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/linus/anaconda3/pkgs
                          /Users/linus/.conda/pkgs
       envs directories : /Users/linus/anaconda3/envs
                          /Users/linus/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.8 Darwin/21.1.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

Hi, I'm trying to install `gst-plugins-bad` with `conda install -c conda-forge gst-plugins-bad` but failed to do so.
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - gst-plugins-bad

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

After some digging, I find that there are no available binary for macos of this package on conda-forge, [see this](https://anaconda.org/conda-forge/gst-plugins-bad). While this repo README do have some MacOS CI flow passed so I reckon this should had MacOS support.

Is this a bug or this repo actually does not have MacOS support ? Thanks for checking by!

### PR DESCRIPTION
**Pull request by lamhoangtung**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR attempt to fix #9

### CODE REVIEW

**Comment by kuepe-sl** [comment]
The Mac OS X pipeline fails with lots of errors in `.m` files, so I can't merge this.

The Linux build fails with an error related to the Meson build system, but that shouldn't be your fault.

**Comment by kuepe-sl** [comment]
Okay, I found the issue with the Linux build:

It is this line: https://github.com/conda-forge/gst-plugins-bad-feedstock/blob/fc8227dc735dae3ebb32f3ec1bbdfeb7e5555306/recipe/build.sh#L16

The option apparently was unused for some time now and can probably safely removed.
With meson 0.59 it would throw a warning while with meson 0.60 it now throws an error.

This doesn't solve the issue with the osx build though.

**Comment by lamhoangtung** [comment]
Thanks @kuepe-sl for the help. I will try to resolve the issue with MacOS then cc you for review again

**Comment by hmaarrfk** [comment]
See #30 and the work done in #27 to find the correct build parameters

**Pull request closed without merging**
